baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "de"
defaultContentLanguage = "de"
title = "Rechtsanwalt Ayaz"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""
  favicon = "favicon-32x32.png"

  [params.homepage]
    sticky_header = true
    show_contact_box = true      # show / hide the contaxt box on the homepage
    show_services_button = false # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/a_mobile.svg"
    mobile_height = "36px"
    desktop = "images/logo/rechtsanwalt_ayaz.svg"
    desktop_height = "36px"
    alt = "Rechtsanwalt Ayaz"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#e5261f"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#fff6f8"
    grey = "#5c5a5a"

  [params.seo]
    meta_twitter_site = ""
    meta_twitter_creator = ""
    meta_og_image = "meta-image.jpg"

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

[menu]
  # Main Menu
  [[menu.main]]
    name = "Leistungen"
    url = "/services/"
    weight = 1

  [[menu.main]]
    name = "Kosten"
    url = "/kosten/"
    weight = 2

  [[menu.main]]
    name = "Ãœber mich"
    url = "/ueber-mich/"
    weight = 3

  [[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Start"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 2
